import type { Metadata } from "next";
import "./globals.css";
import ClientLayout from "./ClientLayout"; // path sesuai lokasi file kamu
import BackgroundMusic from "@/components/BackgroundMusic";
import MusicPlayer from "@/components/MusicPlayer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <ClientLayout>
          {children}
        </ClientLayout>
      </body>
    </html>
  );
}
